name: Push Image

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag
        required: true
      latest:
        type: boolean
        description: Tag as latest

jobs:
  push:
    name: Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: skhrvg
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            skhrvg/ical-unprivate:${{ github.event.inputs.tag }}
            ${{ if github.event.inputs.latest == 'true' }}skhrvg/ical-unprivate:latest${{ endif }}
